name: 'Maven-Lockfile' 
description: 'This action generates a lockfile for a Maven project.' 
branding:
  icon: 'lock'
  color: 'blue'
inputs:
  github-token: 
    description: 'GitHub token'
    required: true
  commit-lockfile: 
    description: 'Commit the lockfile to the repository'
    required: false
    default: 'true'
  commit-message:
    description: 'Commit message for the lockfile'
    required: false
    default: 'chore: update lockfile'
  commit-author:
    description: |
        '
        Author for the lockfile commit. GitHub provides three values for this field.
        - github_actor -> UserName <UserName@users.noreply.github.com>
        - user_info -> Your Display Name <your-actual@email.com>
        - github_actions -> github-actions <email associated with the github logo
        '
    required: false
    default: 'github_actions'
  include-maven-plugins:
    description: 'Include Maven plugins in the lockfile'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.8.2
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash


    - name: Get all changed pom.xml file(s)
      id: changed-files
      uses: tj-actions/changed-files@b2d17f51244a144849c6b37a3a6791b98a51d86f # v35
      with:
        files: |
              **/pom.xml
    - name: print all changed files
      run: echo all changed files are ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
    - name: Set POM_CHANGED environment variable
      run: echo "POM_CHANGED=${{ steps.changed-files.outputs.any_changed}}" >> $GITHUB_ENV
      shell: bash
    - name: print POM-CHANGED
      run: echo "pom changed ${{ env.POM_CHANGED }}"
      shell: bash

    - id: action
      run: ~/.jbang/bin/jbang --repos 'mavencentral' io.github.chains-project:maven-lockfile-github-action:${project.version}
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - id: commit-lockfile
      if: inputs.commit-lockfile == 'true'
      uses: EndBug/add-and-commit@b97a9fe893e2984b63d00feaee5922e16ab1cc1e # v9
      with:
          default_author: ${{ inputs.commit-author }}
          message: ${{ inputs.commit-message }}
