name: 'Maven-Lockfile' 
description: 'This action generates a lockfile for a Maven project.' 
inputs:
  github-token: 
    description: 'GitHub token'
    required: true
runs:
  using: "composite" 
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@
      with:
          java-version: 11
          maven-version: '3.8.1'
    - run: curl -Ls https://sh.jbang.dev | bash -s - app setup 
      shell: bash
    - run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/chains-project/maven-lockfile' --repos 'mavencentral' io.github.chains-project:maven-lockfile-github-action:1.0.0
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }} 
        GITHUB_TOKEN: ${{ inputs.github-token }} 