name: 'Maven-Lockfile' 
description: 'This action generates a lockfile for a Maven project.' 
branding:
  icon: 'lock'
  color: 'blue'
inputs:
  github-token: 
    description: 'GitHub token'
    required: true
  commit-lockfile: 
    description: 'Commit the lockfile to the repository in case the pom.xml or workflow file has updated. If this is false or the pom.xml and workflow.yml files are unchanged the action will verify the current lockfile.json.'
    required: false
    default: 'true'
  commit-message:
    description: 'Commit message for the lockfile'
    required: false
    default: 'chore: update lockfile'
  include-maven-plugins:
    description: 'Include Maven plugins in the lockfile'
    required: false
    default: 'false'
  lockfile-name:
    description: 'Name of the lockfile (default="lockfile.json")'
    required: false
    default: 'lockfile.json'
  workflow-filename:
    description: 'Name of the workflow file'
    required: false
    default: 'Lockfile.yml'
runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ inputs.github-token }}
    - name: Setup Java
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - name: Get all changed pom.xml and workflow file(s)
      id: changed-files
      uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46
      with:
        files: |
              **/pom.xml
              **/${{ inputs.workflow-filename}}
    - name: print all changed files
      run: echo all changed files are ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
    - name: Set POM_CHANGED environment variable
      run: echo "POM_CHANGED=${{ steps.changed-files.outputs.any_changed}}" >> $GITHUB_ENV
      shell: bash
    - name: print POM-CHANGED
      run: echo "pom changed ${{ env.POM_CHANGED }}"
      shell: bash
    - name: Set COMMIT_UPDATED_LOCKFILE environment variable
      run: echo "COMMIT_UPDATED_LOCKFILE=${{ inputs.commit-lockfile }}" >> $GITHUB_ENV
      shell: bash
    - id: action
      run: ~/.jbang/bin/jbang --repos 'mavencentral' io.github.chains-project:maven-lockfile-github-action:5.4.2-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - id: commit-lockfile
      if: inputs.commit-lockfile == 'true'
      uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # 5.1.0
      with:
          commit_message: ${{ inputs.commit-message }}
