name: 'Maven-Lockfile' 
description: 'This action generates a lockfile for a Maven project.' 
branding:
  icon: 'lock'
  color: 'blue'
inputs:
  github-token: 
    description: 'GitHub token'
    required: true
  commit-lockfile: 
    description: 'Commit the lockfile to the repository'
    required: false
    default: 'true'
  pom-changed: 
    description: 'Whether the POM file has changed'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - name: Get changed files
      id: changed-files2
      uses: tj-actions/changed-files@v35
      with:
        since_last_remote_commit: true 
        
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

    - name: List all changed files
      shell: bash
      run: |
          for file in ${{ steps.changed-files2.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
    - name: Get all changed pom.xml file(s)
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
              **/pom.xml
    - name: print all changed files
      run: echo all changed files are ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
    - name: Set pom-changed environment variable
      run: echo "pom-changed=${{ steps.changed-files.outputs.any_changed}}" >> $GITHUB_ENV
      shell: bash
    - name: print pom-changed
      run: echo "pom changed ${{ env.pom-changed }}"
      shell: bash
    - id: action
      run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/chains-project/maven-lockfile/' io.github.chains-project:maven-lockfile-github-action:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        POM_CHANGED: ${{ env.pom-changed }}