name: 'Maven-Lockfile' 
description: 'Description of my action' 
inputs:
  github-token: 
    description: 'GitHub token'
    required: true
runs:
  using: "composite" 
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: sudo apt install maven
      shell: bash
    - run: curl -Ls https://sh.jbang.dev | bash -s - app setup 
      shell: bash
    - run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/chains-project/maven-lockfile' io.github.chains_project.maven_lockfile:maven_lockfile_action:1.0.0
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }} 
        GITHUB_TOKEN: ${{ inputs.github-token }} 
