name: 'Maven-Lockfile' 
description: 'This action generates a lockfile for a Maven project.' 
branding:
  icon: 'lock'
  color: 'blue'
inputs:
  github-token: 
    description: 'GitHub token'
    required: true
  commit-lockfile: 
    description: 'Commit the lockfile to the repository in case the pom.xml or workflow file has updated. If this is false or the pom.xml and workflow.yml files are unchanged the action will verify the current lockfile.json.'
    required: false
    default: 'true'
  commit-message:
    description: 'Commit message for the lockfile'
    required: false
    default: 'chore: update lockfile'
  commit-author:
    description: |
        '
        Author for the lockfile commit. GitHub provides three values for this field.
        - github_actor -> UserName <UserName@users.noreply.github.com>
        - user_info -> Your Display Name <your-actual@email.com>
        - github_actions -> github-actions <email associated with the github logo
        '
    required: false
    default: 'github_actions'
  include-maven-plugins:
    description: 'Include Maven plugins in the lockfile'
    required: false
    default: 'false'
  lockfile-name:
    description: 'Name of the lockfile (default="lockfile.json")'
    required: false
    default: 'lockfile.json'
  workflow-filename:
    description: 'Name of the workflow file'
    required: false
    default: 'Lockfile.yml'
runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        token: ${{ inputs.github-token }}
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.8.2
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash


    - name: Get all changed pom.xml and lockfile.json file(s)
      id: changed-files
      uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366 # v45
      with:
        files: |
              **/pom.xml
              **/${{ inputs.workflow-filename}}
    - name: print all changed files
      run: echo all changed files are ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
    - name: Set POM_CHANGED environment variable
      run: echo "POM_CHANGED=${{ steps.changed-files.outputs.any_changed}}" >> $GITHUB_ENV
      shell: bash
    - name: print POM-CHANGED
      run: echo "pom changed ${{ env.POM_CHANGED }}"
      shell: bash
    - name: Set COMMIT_UPDATED_LOCKFILE environment variable
      run: echo "COMMIT_UPDATED_LOCKFILE=${{ inputs.commit-lockfile }}" >> $GITHUB_ENV
      shell: bash

    - id: action
      run: ~/.jbang/bin/jbang --repos 'mavencentral' io.github.chains-project:maven-lockfile-github-action:5.3.0
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - id: commit-lockfile
      if: inputs.commit-lockfile == 'true'
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
      with:
          default_author: ${{ inputs.commit-author }}
          message: ${{ inputs.commit-message }}
