name: 'Maven-Lockfile' 
description: 'This action generates a lockfile for a Maven project.' 
branding:
  icon: 'lock'
  color: 'blue'
inputs:
  github-token: 
    description: 'GitHub token'
    required: true
  commit-lockfile: 
    description: 'Commit the lockfile to the repository'
    required: false
    default: 'true'
  POM-CHANGED: 
    description: 'Whether the POM file has changed'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - name: Set pom-changed
      if: inputs.POM-CHANGED == 'false'
      run: echo "::set-output name=pom-changed::true"
      shell: bash
    - id: action
      run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/chains-project/maven-lockfile/' --repos 'mavencentral' io.github.chains-project:maven-lockfile-github-action:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        action: "generate"
