FROM debian:bullseye-slim

# install java
ENV PATH=$PATH:/opt/java/jdk-17/bin
RUN apt-get update && apt-get install --yes --no-install-recommends openjdk-17-jdk-headless \
  maven
RUN chown 1001 / \
  && chmod "g+rwX" / \
  && chown 1001:root /
COPY --chown=1001:root build/*-runner /application
EXPOSE 8080
USER 1001

CMD ["/application", "-Dquarkus.http.host=0.0.0.0"]