name: Maven test
on:
  workflow_dispatch:
  pull_request:

permissions:
  id-token: write
  contents: read
jobs:
  maven-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            oss.sonatype.org:443
            maven.artifacts.atlassian.com:443
            packages.atlassian.com:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443
            repo.spring.io:443
            tuf-repo-cdn.sigstore.dev:443
            fulcio.sigstore.dev:443
            rekor.sigstore.dev:443

      - name: Checkout repostiory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Verify action checksums
        uses: chains-project/maven-lockfile/.github/actions/ghasum@3ddcf33c03217482c614440fd714375e9053e732 # 5.16.0

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: mvn clean verify
        run: mvn clean verify

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package

      - name: Run doc check
        run: mvn org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar

      - name: Run spotless check
        run: mvn spotless:check

      - name: Check maven pom quality
        run: mvn org.kordamp.maven:pomchecker-maven-plugin:1.9.0:check-maven-central -D"checker.release=false"

  reproducibility:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            fulcio.sigstore.dev:443
            github.com:443
            maven.artifacts.atlassian.com:443
            objects.githubusercontent.com:443
            oss.sonatype.org:443
            packages.atlassian.com:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443
            repo.spring.io:443
            tuf-repo-cdn.sigstore.dev:443

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Verify action checksums
        uses: chains-project/maven-lockfile/.github/actions/ghasum@3ddcf33c03217482c614440fd714375e9053e732 # 5.16.0

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: First build
        run: mvn --batch-mode --update-snapshots clean package -DskipTests

      - name: Save checksums of first build
        run: sha256sum target/*.jar > /tmp/checksums.txt

      - name: Rebuild
        run: mvn --batch-mode clean package -DskipTests

      - name: Compare JARs from both builds
        run: sha256sum -c /tmp/checksums.txt
