name: Docker
on:
  push:
    branches:
      - main
      - dev
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: cd github_action  && mvn --batch-mode --update-snapshots clean package deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  check-lockfile:
        runs-on: ubuntu-latest
        needs: build-and-publish
        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
        - name: pull image with current version from maven 
          uses: docker://ghcr.io/chains-project/maven-lockfile:dev
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}


