# publish a docker image to ghcr.io for pushes to main or dev with github actions

name: Docker
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package
      - name: Build the Docker image
        run: cd github_action && docker build -f src/main/docker/Dockerfile.jvm -t chains/lockfile_action .
      - name: Log into registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Push image
        run: docker push ghcr.io/$GITHUB_REPOSITORY:latest


