name: Ensure release action is currently not running

on:
  pull_request:

jobs:
  ensure_notrunning_release:
    name: Ensure release action is not running

    runs-on: ubuntu-latest

    steps:
      - name: check_release_running
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENTLY_RUNNING=$(gh run list -w jreleaser.yml --json status --jq '[.[] | select(.status == "queued" or .status == "in_progress" or .status == "requested" or .status == "waiting" or .status == "pending" or .status == "action_required")][0]')
          if [[ "$CURRENTLY_RUNNING" == *"status"* ]]; then
            echo "❌ Release workflow is currently running. Please wait for it to finish then rerun this workflow to proceed."
            exit 1
          else
            echo "✅ No running release workflows detected."
          fi
        shell: bash