name: ghasum
on:
  pull_request:

permissions: read-all

jobs:
  update:
    name: Update gha.sum
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To push a commit
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443

      - name: Checkout repository
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Update gha.sum
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: chains-project/maven-lockfile/.github/actions/ghasum@965b5aeb7c07fc4483409f041706e6642e6967a7 # 5.17.3
        with:
          mode: update

      - name: Commit gha.sum
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore: update ghasum checksums"
          file_pattern: .github/workflows/gha.sum

      - name: Skip update (fork)
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: echo "::warning::Cannot auto-update gha.sum for fork PRs. If actions were updated, please run ghasum update manually."
