on:
  pull_request:
jobs:
  jbang:
    runs-on: ubuntu-latest
    name: smoke test against different repos
    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
          java-version: 11
          maven-version: '3.8.1'
          checkout-fetch-depth: 0
    - uses: actions/cache@v3
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - name: Set up Maven
      run: sudo apt install maven
    - name: jbang
      uses: jbangdev/jbang-action@v0.106.1
      with:
        script: ".github/smoketest/TestJava.java"
      env:
        JBANG_REPO: /root/.jbang/repository
        GITHUB_TOKEN: $
        WORKING_DIRECTORY: ${{ env.working-directory }}